- hosts: elasticsearch
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.8.0
    es_heap_size: "1536M"
    #   es_java_opts: "-Duser.timezone='Europe/London' -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8111 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=`hostname` -Dcom.sun.management.snmp.port=9999 -Dcom.sun.management.snmp.acl=false" 
    es_config_default: "etc-default-elasticsearch"
    es_config:
      cluster.name: "elasticsearch-cluster"
      cluster.initial_master_nodes: [ "elasticsearch01", "elasticsearch02" , "elasticsearch03" ]
      network.host: "0.0.0.0"
      discovery.zen.ping.unicast.hosts: [ "elasticsearch01", "elasticsearch02" , "elasticsearch03" ]
      http.port: 9200
      bootstrap.memory_lock: false
      # 20200202 for bitbucket https://confluence.atlassian.com/bitbucketserver/how-to-install-and-configure-a-remote-elasticsearch-instance-815577748.html
      # probably only needs to be done on one?..
      #  action.auto_create_index: ".watches,.triggered_watches,.watcher-history-*"
      #  2020-03-10 remving so it can hopefully upgrade properly via apt...
      #    es_plugins:
      #- plugin: ingest-attachment
      #  state: absent
      #  # version: 7.6.0
      #es_plugins_reinstall: true

    #   - elasticsearch_plugin:
    # name: ingest-attachment
    # version: 7.6.0
    #  name: append es_java_opts to /etc/default/elasticsearch
    #    lineinfile:
    #      dest: /etc/default/elasticsearch
    #      regexp: ES_JAVA_OPTS
    #      line: ES_JAVA_OPTS="-Duser.timezone='Europe/London' -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8111 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=`hostname` -Dcom.sun.management.snmp.port=9999 -Dcom.sun.management.snmp.acl=false"
