# kibana only runs on x64 hosts, and the gateway machines are still on 32bit...

- hosts: logstash
  roles:
    - role: geerlingguy.kibana
  vars:
    kibana_version: "7.5.2"
    kibana_package: kibana
    kibana_package_state: present
    kibana_service_state: started
    kibana_service_enabled: true
    kibana_config_template: kibana.yml.j2
    kibana_config_file_path: /etc/kibana/kibana.yml
    kibana_server_port: 5601
    kibana_server_host: "logstash"
    kibana_elasticsearch_url: "http://gateway:9200"
    kibana_elasticsearch_username: ""
    kibana_elasticsearch_password: ""
